Вправа 1  
Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [1]:
import numpy as np

def task_1_numpy(n):
    diag = np.arange(1, n + 1)
    result = np.diag(diag)
    return result

n = int(input("Enter the value of n: "))
print(task_1_numpy(n))


[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [2]:
def task_1_iterative(n):
    result = []
    for i in range(n):
        row = [0] * n
        row[i] = i + 1
        result.append(row)
    return result

n = int(input("Enter the value of n: "))
print(task_1_iterative(n))


[[1, 0, 0], [0, 2, 0], [0, 0, 3]]


Вправа 6  
З клавіатури вводиться масив. Замінити всі ненульові
елементи на –1.

In [4]:
def task_6_numpy(arr):
    return np.where(arr != 0, -1, arr)

user_input = input("Enter array elements separated by space: ")
arr = np.array(list(map(int, user_input.split())))
print(task_6_numpy(arr))


[-1 -1 -1 -1 -1  0 -1 -1  0 -1]


In [5]:
def task_6_iterative(arr):
    result = [-1 if x != 0 else x for x in arr]
    return result

user_input = input("Enter array elements separated by space: ")
arr = list(map(int, user_input.split()))
print(task_6_iterative(arr))

[-1, -1, -1, -1, 0, -1, -1, -1, 0]


Вправа 7  
З клавіатури вводиться масив. Замінити всі нульові
елементи на –1.

In [6]:
def task_7_numpy(arr):
    return np.where(arr == 0, -1, arr)

user_input = input("Enter array elements separated by space: ")
arr = np.array(list(map(int, user_input.split())))
print(task_7_numpy(arr))


[  5   2  21  -1   1   2 300  -1]


In [7]:
def task_7_iterative(arr):
    result = [-1 if x == 0 else x for x in arr]
    return result

user_input = input("Enter array elements separated by space: ")
arr = list(map(int, user_input.split()))
print(task_7_iterative(arr))


[2, 1, -1, 2, 5, 1, -1]


Вправа 9  
Вводиться число n. Створити масив значень від n до 0.

In [9]:
def task_9_numpy(n):
    return np.arange(n, -1, -1)

n = int(input("Enter the value of n: "))
print(task_9_numpy(n))


[10  9  8  7  6  5  4  3  2  1  0]


In [10]:
def task_9_iterative(n):
    return list(range(n, -1, -1))

n = int(input("Enter the value of n: "))
print(task_9_iterative(n))


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


Вправа 10  
Вводиться числа n i m. Створити масив випадкових
значень n×m і обчислити мінімальне, максимальне значення, середнє та
середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [12]:
def task_10_numpy(n, m):
    array = np.random.rand(n, m)
    minimum = np.min(array)
    maximum = np.max(array)
    mean = np.mean(array)
    std_dev = np.round(np.std(array), 3)
    return minimum, maximum, mean, std_dev

n, m = map(int, input("Enter n and m separated by space: ").split())
result = task_10_numpy(n, m)
print("Minimum:", result[0])
print("Maximum:", result[1])
print("Mean:", result[2])
print("Standard Deviation:", result[3])


Minimum: 0.0030529606533317155
Maximum: 0.9868177575239394
Mean: 0.5689276980729471
Standard Deviation: 0.271


In [13]:
import random

def task_10_iterative(n, m):
    array = [[random.random() for _ in range(m)] for _ in range(n)]
    flatten_array = [item for sublist in array for item in sublist]
    minimum = min(flatten_array)
    maximum = max(flatten_array)
    mean = sum(flatten_array) / len(flatten_array)
    std_dev = round((sum((x - mean) ** 2 for x in flatten_array) / len(flatten_array)) ** 0.5, 3)
    return minimum, maximum, mean, std_dev

n, m = map(int, input("Enter n and m separated by space: ").split())
result = task_10_iterative(n, m)
print("Minimum:", result[0])
print("Maximum:", result[1])
print("Mean:", result[2])
print("Standard Deviation:", result[3])


Minimum: 0.016723166324256633
Maximum: 0.8779204951815105
Mean: 0.45064050820239815
Standard Deviation: 0.266


Вправа 11  
Створити масив одиниць розміром n×n та додати до
нього «рамку», що утворюється з 0.

In [15]:
def task_11_numpy(n):
    inner = np.ones((n, n), dtype=int)
    outer = np.pad(inner, pad_width=1, mode='constant')
    return outer

n = int(input("Enter the value of n: "))
print(task_11_numpy(n))


[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [16]:
def task_11_iterative(n):
    outer = [[0] * (n + 2) for _ in range(n + 2)]
    for i in range(1, n + 1):
        for j in range(1, n + 1):
            outer[i][j] = 1
    return outer

n = int(input("Enter the value of n: "))
print(task_11_iterative(n))


[[0, 0, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 0, 0, 0, 0]]


Вправа 15  
Заповнити парні стовпчикі матриці розміром n×n
одиницями, а непарні – нулями.

In [19]:
import numpy as np

def task_15_numpy(n):
    matrix = np.zeros((n, n), dtype=int)
    matrix[:, ::2] = 1
    return matrix

n = int(input("Enter the value of n: "))
print(task_15_numpy(n))


[[1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]]


In [20]:
def task_15_iterative(n):
    matrix = [[1 if j % 2 == 0 else 0 for j in range(n)] for i in range(n)]
    return matrix

n = int(input("Enter the value of n: "))
print(task_15_iterative(n))


[[1, 0, 1, 0, 1], [1, 0, 1, 0, 1], [1, 0, 1, 0, 1], [1, 0, 1, 0, 1], [1, 0, 1, 0, 1]]


Вправа 17  
Заповнити вектор значеннями від 0 до n. Замінити
знаки для всіх значень, що менші за n/2 та більші за 3n/4 на
протилежні.

In [21]:
def task_17_numpy(n):
    vector = np.arange(n)
    condition1 = vector < n/2
    condition2 = vector > 3*n/4
    vector[condition1 | condition2] *= -1
    return vector

n = int(input("Enter the value of n: "))
print(task_17_numpy(n))


[ 0 -1 -2 -3  4  5 -6]


In [22]:
def task_17_iterative(n):
    vector = list(range(n))
    for i in range(len(vector)):
        if vector[i] < n/2 or vector[i] > 3*n/4:
            vector[i] *= -1
    return vector

n = int(input("Enter the value of n: "))
print(task_17_iterative(n))


[0, -1, -2, -3, 4, 5, -6]


Вправа 18  
Згенерувати вектор з n випадкових чисел в діапазоні
від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [23]:
def task_18_numpy(n):
    sequence = np.random.randint(0, 100, n)
    unique_count = len(np.unique(sequence))
    return sequence, unique_count

n = int(input("Enter the value of n: "))
result, unique_count = task_18_numpy(n)
print("In the sequence", result, "- there are", unique_count, "unique numbers.")


In the sequence [85 99 67 18 12 38 74 50 95 72 60 83 70 57 81 72  7 86 45 83 78  7 93 95
  9 43  6  2 26 77] - there are 26 unique numbers.


In [24]:
import random

def task_18_iterative(n):
    sequence = [random.randint(0, 99) for _ in range(n)]
    unique_count = len(set(sequence))
    return sequence, unique_count

n = int(input("Enter the value of n: "))
result, unique_count = task_18_iterative(n)
print("In the sequence", result, "- there are", unique_count, "unique numbers.")


In the sequence [82, 65, 57, 28, 17, 35, 12, 9, 39, 26, 32, 78, 68, 97, 73, 85, 62, 73, 82, 24, 70, 40, 40, 31, 13, 81, 63, 97, 57, 87] - there are 25 unique numbers.


Розв’язати систему алгебраїчних рівнянь за допомогою
формул Крамера і виконати перевірку за допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose().

$$
\begin{cases}
    x₁ + x₂ + 2x₃ + 3x₄ = 1 \\
    3x₁ - x₂ - x₃ - 2x₄ = -4 \\
    2x₁ - 3x₂ - x₃ - x₄ = -6 \\
    x₁ + 2x₂ + 3x₃ - x₄ = -4 
\end{cases}
$$


In [31]:
import numpy as np

# Основна матриця системи рівнянь
A = np.array([[1, 1, 2, 3],
              [3, -1, -1, -2],
              [2, -3, -1, -1],
              [1, 2, 3, -1]])

# Права частина системи рівнянь
B = np.array([1, -4, -6, -4])

# Визначник основної матриці
det_A = np.linalg.det(A)

# Функція для розрахунку розв'язків за допомогою формул Крамера
def kramer_method(A, B):
    solutions = []
    for i in range(A.shape[0]):
        Ai = A.copy()
        Ai[:, i] = B
        det_Ai = np.linalg.det(Ai)
        xi = det_Ai / det_A
        solutions.append(xi)
    return solutions

# Розв'язки за допомогою формул Крамера
kramer_solutions = kramer_method(A, B)

# Розв'язки за допомогою матричного множення
matrix_mul_solution = np.linalg.inv(A) @ B

# Розв'язки за допомогою оберненої матриці
inverse_matrix_solution = np.linalg.inv(A) @ B

# Розв'язки за допомогою функції numpy.linalg.solve()
solve_solution = np.linalg.solve(A, B)

# Виведення результатів
print("Kramer solutions:", kramer_solutions)
print("Matrix multiplication solution:", matrix_mul_solution)
print("Inverse matrix solution:", inverse_matrix_solution)
print("numpy.linalg.solve() solution:", solve_solution)
print("\n")
# Порівняння результатів
print("Results are close (Kramer vs Matrix multiplication):", np.allclose(kramer_solutions, matrix_mul_solution))
print("Results are close (Kramer vs Inverse matrix):", np.allclose(kramer_solutions, inverse_matrix_solution))
print("Results are close (Kramer vs numpy.linalg.solve()):", np.allclose(kramer_solutions, solve_solution))

Kramer solutions: [-0.5555555555555552, 1.888888888888888, -2.0000000000000004, 1.2222222222222228]
Matrix multiplication solution: [-0.55555556  1.88888889 -2.          1.22222222]
Inverse matrix solution: [-0.55555556  1.88888889 -2.          1.22222222]
numpy.linalg.solve() solution: [-0.55555556  1.88888889 -2.          1.22222222]


Results are close (Kramer vs Matrix multiplication): True
Results are close (Kramer vs Inverse matrix): True
Results are close (Kramer vs numpy.linalg.solve()): True


Обчислити значення матричного виразу
а) з використанням універсальних функцій бібліотеки NumPy.
b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
с) для обох випадків підрахувати час виконання скрипту та
зробити висновок.
Порівняти всі рішення за допомогою функції numpy.allclose().  

$$ 2(A+B)(2B-A), $$

де

$$ A = \begin{bmatrix} 2 & 3 & -1 \\ 4 & 5 & 2 \\ -1 & 0 & 7 \end{bmatrix}, $$
$$ B = \begin{bmatrix} -1 & 0 & 5 \\ 0 & 1 & 3 \\ 2 & -2 & 4 \end{bmatrix}. $$

In [45]:
import numpy as np
import time

# Задання матриць A та B
A = np.array([[2, 3, -1], [4, 5, 2], [-1, 0, 7]])
B = np.array([[-1, 0, 5], [0, 1, 3], [2, -2, 4]])

# Обчислення значення матричного виразу з використанням NumPy
start_time = time.time()
result_np = 2 * (A + B) @ (2 * B - A)
numpy_execution_time = time.time() - start_time

# Обчислення значення матричного виразу за допомогою ітеративних конструкцій
start_time = time.time()
result_iterative = np.zeros((len(A), len(B[0])))
for i in range(len(A)):
    for j in range(len(B[0])):
        val = 0
        for k in range(len(B)):
            val += (2 * (A[i][k] + B[i][k]) * (2 * B[k][j] - A[k][j]))  # Виправлення помилки тут
        result_iterative[i][j] = val
iterative_execution_time = time.time() - start_time

# Порівняння результатів за допомогою numpy.allclose()
close_results = np.allclose(result_np, result_iterative)

# Виведення результатів та часу виконання
print("Результат з використанням NumPy:\n", result_np)
print("Результат з використанням ітеративних конструкцій:\n", result_iterative)
print("Результати співпадають:", close_results)
print("Час виконання з використанням NumPy:", numpy_execution_time)
print("Час виконання з використанням ітеративних конструкцій:", iterative_execution_time)


Результат з використанням NumPy:
 [[   8  -56   54]
 [ -30 -100  146]
 [ 118  -82   28]]
Результат з використанням ітеративних конструкцій:
 [[   8.  -56.   54.]
 [ -30. -100.  146.]
 [ 118.  -82.   28.]]
Результати співпадають: True
Час виконання з використанням NumPy: 0.0
Час виконання з використанням ітеративних конструкцій: 0.0
